I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script
    show submarino at 1.0
TypeError: 'float' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    show submarino at 1.0
  File "D:\Desenvolvimento de Games\Ren'py\Engine\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Desenvolvimento de Games\Ren'py\Engine\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "D:\Desenvolvimento de Games\Ren'py\Engine\renpy-8.1.3-sdk\renpy\exports.py", line 745, in show
    img = i(img) # type: ignore
TypeError: 'float' object is not callable

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Acacia: O prólogo do desespero 1.0
Wed Jan 24 16:56:51 2024
